In [29]:
import numpy as np
import tensorflow as tf
import pandas as pd
from tensorflow.keras.applications.inception_v3 import InceptionV3
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [2]:
!wget -O 'input_data_random_800.npy' 'https://drive.google.com/uc?id=10uilSyuHEbl6f6zJgh89_-uRfev8rQ8N&confirm=t'
!wget -O 'videoIDs_random_800.npy' 'https://drive.google.com/uc?id=1-0ZOCy3t7sO5bowBc4AcmOfLacqcRlEI&confirm=t'

--2022-03-12 17:00:59--  https://drive.google.com/uc?id=10uilSyuHEbl6f6zJgh89_-uRfev8rQ8N&confirm=t
Resolving drive.google.com (drive.google.com)... 142.251.6.138, 142.251.6.139, 142.251.6.100, ...
Connecting to drive.google.com (drive.google.com)|142.251.6.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-10-20-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/5bo0a4jfmhn4vd3fc9oofjrtog85himp/1647104400000/17228267550831568869/*/10uilSyuHEbl6f6zJgh89_-uRfev8rQ8N [following]
--2022-03-12 17:00:59--  https://doc-10-20-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/5bo0a4jfmhn4vd3fc9oofjrtog85himp/1647104400000/17228267550831568869/*/10uilSyuHEbl6f6zJgh89_-uRfev8rQ8N
Resolving doc-10-20-docs.googleusercontent.com (doc-10-20-docs.googleusercontent.com)... 172.217.214.132, 2607:f8b0:4001:c05::84
Connecting to doc-10-20-docs.googleusercontent.com (doc-10-20-docs.googleusercontent.com)|172.217

In [3]:
input_data = np.load('input_data_random_800.npy')
videoIDs = np.load('videoIDs_random_800.npy')

In [4]:
last_layer=tf.keras.layers.GlobalAveragePooling2D()
model = InceptionV3(weights="imagenet", include_top=False, input_shape=(224, 224, 3))
out=model.layers[-1].output
avg_pool = tf.keras.layers.GlobalAveragePooling2D()(out)
model=tf.keras.models.Model(inputs=model.input, outputs=avg_pool)
model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss="binary_crossentropy",
    metrics=["acc"],
)
model.summary()

87924736/87910968 [==============================] - 1s 0us/step
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv2d (Conv2D)                (None, 111, 111, 32  864         ['input_1[0][0]']                
                                )                                                                 
                                                                                                  
 batch_normalization (BatchNorm  (None, 111, 111, 32  96         ['conv2d[0][0]']                 
 alization)                  

In [5]:
!mkdir features

In [6]:
for i in range(len(videoIDs)):
  feature_vector=model.predict(input_data[i],batch_size=128)
  path='/content/features/'+videoIDs[i]+'.npy'
  print(i)
  np.save(path, feature_vector)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [11]:
!zip -r features.zip features

  adding: features/ (stored 0%)
  adding: features/yYA7YXIKbg4_9_14.npy (deflated 13%)
  adding: features/rw9h_574HxE_229_236.npy (deflated 13%)
  adding: features/o2X6UCaNqKA_27_36.npy (deflated 13%)
  adding: features/iCiGjZEV7VI_65_75.npy (deflated 14%)
  adding: features/-_hbPLsZvvo_5_8.npy (deflated 12%)
  adding: features/bXsKw3TOQXs_30_55.npy (deflated 14%)
  adding: features/EPXsiQw9vvo_1_12.npy (deflated 12%)
  adding: features/-dm-ds5rRaM_44_52.npy (deflated 14%)
  adding: features/oFUsn1owAbs_158_168.npy (deflated 14%)
  adding: features/eroAmLZ85DI_28_35.npy (deflated 12%)
  adding: features/4QYPZM01xFE_14_26.npy (deflated 14%)
  adding: features/omIPdpxg--4_39_46.npy (deflated 14%)
  adding: features/-Ms9tsWmhyU_80_95.npy (deflated 13%)
  adding: features/ngHDYzhDBk4_5_14.npy (deflated 13%)
  adding: features/MoqC84sXu88_47_59.npy (deflated 15%)
  adding: features/QsvBYKaCXEc_5_15.npy (deflated 16%)
  adding: features/HO_ovIrLWfQ_1_11.npy (deflated 14%)
  adding: features/

In [13]:
from google.colab import drive
drive.mount('/content/gdrive')


Mounted at /content/gdrive


In [14]:
!cp '/content/features.zip' '/content/gdrive/MyDrive/IT416'

In [15]:
!wget -O data.csv 'https://drive.google.com/uc?id=1pCx7XFmjFtD4RfmfKpeZgx8ijaXmZDld&confirm=t'

--2022-03-12 18:04:15--  https://drive.google.com/uc?id=1pCx7XFmjFtD4RfmfKpeZgx8ijaXmZDld&confirm=t
Resolving drive.google.com (drive.google.com)... 74.125.70.138, 74.125.70.100, 74.125.70.139, ...
Connecting to drive.google.com (drive.google.com)|74.125.70.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0s-0c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/at34mdlgqpu05tm8rt7tpooa10hk9pco/1647108225000/04941579238877149480/*/1pCx7XFmjFtD4RfmfKpeZgx8ijaXmZDld [following]
--2022-03-12 18:04:16--  https://doc-0s-0c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/at34mdlgqpu05tm8rt7tpooa10hk9pco/1647108225000/04941579238877149480/*/1pCx7XFmjFtD4RfmfKpeZgx8ijaXmZDld
Resolving doc-0s-0c-docs.googleusercontent.com (doc-0s-0c-docs.googleusercontent.com)... 172.253.114.132, 2607:f8b0:4001:c22::84
Connecting to doc-0s-0c-docs.googleusercontent.com (doc-0s-0c-docs.googleusercontent.com)|172.253

In [18]:
df=pd.read_csv('data.csv')
df

VideoID                                       Description
0      -4wsuPCjDBc_5_15       a squirrel is eating a peanut in it s shell
1      -4wsuPCjDBc_5_15                              a chipmunk is eating
2      -4wsuPCjDBc_5_15                     a chipmunk is eating a peanut
3      -4wsuPCjDBc_5_15                        a chipmunk is eating a nut
4      -4wsuPCjDBc_5_15                        a squirrel is eating a nut
...                 ...                                               ...
80783   zxB4dFJhHR8_1_9                           a girl riding a bicycle
80784   zxB4dFJhHR8_1_9  a smiling girl wearing backpack is riding a bike
80785   zxB4dFJhHR8_1_9               the girl rode her bike at the beach
80786  zzit5b_-ukg_5_20                  a boy is doing exercise by cycle
80787  zzit5b_-ukg_5_20                a boy is doing exercise on machine

[80788 rows x 2 columns]

In [21]:
df.loc[df['VideoID']==videoIDs[0]]

VideoID                                        Description
2359  0GXq1An3yHI_22_35                              a woman chops up curd
2360  0GXq1An3yHI_22_35                  a cook is chopping green chillies
2361  0GXq1An3yHI_22_35                     a man dices some green peppers
2362  0GXq1An3yHI_22_35                        a man is chopping scallions
2363  0GXq1An3yHI_22_35       a man is finely chopping some green chillies
2364  0GXq1An3yHI_22_35  a person is slicing green chilli into small pi...
2365  0GXq1An3yHI_22_35  a person is using a knife to chop a vegetable ...
2366  0GXq1An3yHI_22_35                     green chili s are being sliced
2367  0GXq1An3yHI_22_35                  green chillies are chopped finely
2368  0GXq1An3yHI_22_35                          peppers are being chopped
2369  0GXq1An3yHI_22_35                         someone is chopping celery
2370  0GXq1An3yHI_22_35                         someone is dicing a pepper
2371  0GXq1An3yHI_22_35                        the cook is slicing peppers
2372  0GXq1An3yHI_22_35  a chef making buttermilk from north indian cur...
2373  0GXq1An3yHI_22_35                          a grinder is in the table
2374  0GXq1An3yHI_22_35             a person is cutting a slices of pepper
2375  0GXq1An3yHI_22_35                             beans is being chopped
2376  0GXq1An3yHI_22_35           very very super butter milk curd prepare
2377  0GXq1An3yHI_22_35                 a chef is chopping up some peppers
2378  0GXq1An3yHI_22_35                         a cook cuts up some celery
2379  0GXq1An3yHI_22_35                           a man cooking his kichen
2380  0GXq1An3yHI_22_35                   a man is chopping a chile pepper
2381  0GXq1An3yHI_22_35              a man is chopping green chili peppers
2382  0GXq1An3yHI_22_35                   a man is chopping green chillies
2383  0GXq1An3yHI_22_35                           a man is chopping olives
2384  0GXq1An3yHI_22_35              a man is chopping some green chillies
2385  0GXq1An3yHI_22_35                          a man is cutting chillies
2386  0GXq1An3yHI_22_35                           a man is slicing a chili
2387  0GXq1An3yHI_22_35           a person is chopping green chili peppers
2388  0GXq1An3yHI_22_35                       a person is chopping peppers
2389  0GXq1An3yHI_22_35                       a person is chopping peppers
2390  0GXq1An3yHI_22_35                    a person is slicing up a pepper
2391  0GXq1An3yHI_22_35  a professional chef always braces his knuckles...
2392  0GXq1An3yHI_22_35               a woman is chopping up a green chili
2393  0GXq1An3yHI_22_35          indian origin dish preparing instructions
2394  0GXq1An3yHI_22_35                          somebody is cutting chili
2395  0GXq1An3yHI_22_35                     someone chopped up green onion
2396  0GXq1An3yHI_22_35                    someone chopping up a vegetable
2397  0GXq1An3yHI_22_35                        someone cut up green onions
2398  0GXq1An3yHI_22_35                      someone is chopping a chillie
2399  0GXq1An3yHI_22_35                         someone is chopping chives
2400  0GXq1An3yHI_22_35                  someone is chopping greenchillies
2401  0GXq1An3yHI_22_35                        someone is chopping peppers
2402  0GXq1An3yHI_22_35                        someone is cutting a pepper
2403  0GXq1An3yHI_22_35          someone is cutting the slices of chilling
2404  0GXq1An3yHI_22_35                      someone is slicing a vegtable
2405  0GXq1An3yHI_22_35          someone is thinly slicing a banana pepper
2406  0GXq1An3yHI_22_35               the person is cutting up hot peppers
2407  0GXq1An3yHI_22_35                       the person is dicing peppers

In [34]:
train_list=[]
vocab_list=[]
for i in range(len(videoIDs)):
  df_temp=df.loc[df['VideoID']==videoIDs[i]]
  for _, row in df_temp.iterrows():
    caption = "<bos> " + row['Description'] + " <eos>"
    if len(caption.split()) > 10 or len(caption.split()) < 6:
        continue
    else:
        train_list.append([caption, videoIDs[i]])
        
training_list = train_list[:20000]
validation_list = train_list[20000:]

for train in training_list:
    vocab_list.append(train[0])
tokenizer = Tokenizer(num_words=1500)
tokenizer.fit_on_texts(vocab_list)

24495


In [35]:
encoder_input_data = []
decoder_input_data = []
decoder_target_data = []
videoId = []
videoSeq = []
for idx, cap in enumerate(training_list):
    caption = cap[0]
    videoId.append(cap[1])
    videoSeq.append(caption)
train_sequences = tokenizer.texts_to_sequences(videoSeq)
print(train_sequences)
train_sequences = np.array(train_sequences)
train_sequences = pad_sequences(train_sequences, padding='post', truncating='post',
                                maxlen=10)
file_size = len(train_sequences)
print(file_size)

[[1, 3, 7, 222, 40, 2], [1, 3, 141, 4, 65, 158, 918, 2], [1, 3, 6, 611, 28, 158, 415, 2], [1, 3, 6, 4, 65, 1466, 2], [1, 3, 6, 4, 757, 65, 28, 158, 918, 2], [1, 158, 333, 75, 9, 68, 151, 2], [1, 158, 918, 9, 390, 757, 2], [1, 415, 9, 68, 390, 2], [1, 22, 4, 65, 919, 2], [1, 22, 4, 220, 3, 402, 2], [1, 5, 141, 4, 26, 415, 2], [1, 3, 4, 11, 5, 162, 2], [1, 3, 12, 4, 20, 3, 108, 25, 402, 2], [1, 697, 4, 68, 390, 2], [1, 97, 97, 636, 154, 296, 698, 2], [1, 3, 67, 4, 65, 40, 28, 415, 2], [1, 3, 141, 89, 40, 28, 919, 2], [1, 3, 6, 37, 32, 109, 2], [1, 3, 6, 4, 65, 3, 402, 2], [1, 3, 6, 4, 65, 158, 333, 415, 2], [1, 3, 6, 4, 65, 158, 918, 2], [1, 3, 6, 4, 65, 2], [1, 3, 6, 4, 65, 28, 158, 918, 2], [1, 3, 6, 4, 20, 918, 2], [1, 3, 6, 4, 26, 3, 333, 2], [1, 3, 12, 4, 65, 158, 333, 415, 2], [1, 3, 12, 4, 65, 415, 2], [1, 3, 12, 4, 65, 415, 2], [1, 3, 12, 4, 26, 40, 3, 402, 2], [1, 3, 7, 4, 65, 40, 3, 158, 333, 2], [1, 525, 155, 81, 2], [1, 375, 4, 20, 333, 2], [1, 22, 390, 40, 158, 53, 2], [1, 2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if sys.path[0] == '':


In [40]:
a = tf.keras.utils.to_categorical([0, 1, 2, 3], num_classes=6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]
